// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hospital2.Models;

public partial class LeaveRequests
{
    [Key]
    public int Id { get; set; }

    [DisplayName("Employee")]
    public int UserDetailId { get; set; }

    [DisplayName("Type")]
    public int LeaveTypeId { get; set; }

    [DisplayName("Start")]
    public DateTime? StartDate { get; set; }

    [DisplayName("End")]
    public DateTime? EndDate { get; set; }

    [DisplayName("Status")]
    public int LeaveStatusId { get; set; }

    public string Reason { get; set; }

    public decimal? Days { get; set; }

    [DisplayName("Document")]
    public byte[] UploadDocument { get; set; }

    [DisplayName("Approved By")]
    public string ApprovedByUserDetailId { get; set; }

    [DisplayName("Date Approved")]
    public DateTime? DateApproved { get; set; }

    [DisplayName("Rejected By")]
    public string RejectedByUserDetailId { get; set; }

    [DisplayName("Date Rejected")]
    public DateTime? DateRejected { get; set; }

    public virtual LeaveStatus LeaveStatus { get; set; }

    public virtual LeaveTypes LeaveType { get; set; }

    public virtual UserDetails UserDetail { get; set; }
}