// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hospital2.Models;

public partial class UserDetails
{
    [Key]
    public int Id { get; set; }

    [Required]
    [DisplayName("Full Name")]
    public string AspNetUserId { get; set; }

    [DisplayName("Department")]
    public int DepartmentId { get; set; }

    [DisplayName("Work Title")]
    public int WorkTitleId { get; set; }

    public virtual Departments Department { get; set; }

    public virtual ICollection<LeaveRequests> LeaveRequests { get; set; } = new List<LeaveRequests>();

    public virtual ICollection<OncallRequests> OncallRequests { get; set; } = new List<OncallRequests>();

    public virtual ICollection<ShiftDetails> ShiftDetails { get; set; } = new List<ShiftDetails>();

    public virtual WorkTitles WorkTitle { get; set; }
}