// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hospital2.Models;

public partial class WorkTitles
{
    [Key]
    public int Id { get; set; }

    [DisplayName("Work Title")]
    public string WorkTitleName { get; set; }

    public virtual ICollection<LeaveConditions> LeaveConditions { get; set; } = new List<LeaveConditions>();

    public virtual ICollection<UserDetails> UserDetails { get; set; } = new List<UserDetails>();
}